### ISSUE TITLE
[exercise] - runcmd specs - redirection

### ISSUE THREAD

**Issue by Henrique1792** [SOII-2016/shue#1]
Hi!

How should we deal with redirection? "runcmd.txt" specifies, on line 74:

> 74   Subprocess's standard input, output and error may be redirected. To that
 75   end the caller must pass a pointer to an array of tree integers as the
 76   argument 'io'.  The integers are interpreted as files descriptors of
 77   previously opened files. Files are neither closed nor flushed by the
 78   function.  runcmd() does not check if write/write operations are
 79   correctly performed.

So - if I get a command with '>' operand and a destiny file:
a) I have to concern about the operand AND the destiny file, using "open" function? Even for **stdin** and **stderr**

**OR**

b) I have to consider the opened file descriptors and runcmd just uses dup2 to duplicate 'em and redirect everything.

**Comment by monacofj** [comment]
Well, a little further down in runcmd.txt, the section NOTES says

`       Unlike 'system' function of standard C
        library, function runcmd() does not interpret any other character other
        than a trailing '&' as a special symbol. For instance, characters '<' 
        and '|', understood as the redirection and pipe symbols by /bin/sh, 
        respectively, are interpreted as any other character by runcmd ().
        For instance, if 'command' is 'prog arg > out', 'prog' is executed
        with arguments 'arg', '>' and 'out'. Input-output redirection either
        for files or pipes can be achieved by means of built-in functionality
        accessible with 'io' parameter.
`
This implies that runcmd() does not need to concern with redirection operand at all. If the command line has a '>' symbol, the function will interpret it as any other argument.

If the user wants to redirect the command foo's output to the file bar, it will do something like:

` fd = open ("somepath/bar", SOME_FLAGS);
  io[0] = fileno(stdin);    /* Leave as is*/
  io[1]=fd;                     /* Use this as the the standard output*/
  io[2]= fileno(stdout);  /* Leave as is */
  runcmd ("foo", &result,

**Comment by Henrique1792** [comment]
ok, thanks! =D
