### ISSUE TITLE
(RunCmd) -

### ISSUE THREAD

**Issue by Henrique1792** [SOII-2016/shue#10]
How the:
*Command ./t2 14    (10306,   normal,   7, block, exec yes)
T3 001 whether lib didn't mess with child's descriptors          NO *

works?

I believe I wrote the File redirection nicely, but I dunno exactly
how to correct this error.

**Comment by monacofj** [comment]
T3  001 checks for file descriptor leaks across exec. The test verifies if  subprocess has only the standard descriptors 0, 1 and 2.  Opening a new file or pipe before exec is one reason why the test fails. If this is the case, consider O_CLOEXEC flag.
