### ISSUE TITLE
Problems Linking our project

### ISSUE THREAD

**Issue by Henrique1792** [SOII-2016/shue#2]
We gotta an issue linking the exercise to test-runcmd.

We followed the instructions in README - it created the lib and include folder, but it's not executing.
I'm certain about this 'cause we added a printf to correct the 2 remaining issues (like a debug flag), and the execution didn't show 'em.

What it could be?

**Comment by monacofj** [comment]
How exactly are you doing? Would you paste the command line actions and results?

**Comment by Henrique1792** [comment]
I build it using your makefile, inside posixeg and added the PREFIX using the path for our file.

After I used the make command using specified enviroment variables with the right path.
the "lib" and "include" directories are created, but it doesn't link.

**Comment by Henrique1792** [comment]
at first: 
$ make clean
$ make PREFIX="path to our project" install
$ make make LDFLAGS="-L"path to our project" -Wl,-rpath="path to our project"/lib" \
          CPPFLAGS="-I"Path to our project"/local/include"

**Comment by monacofj** [comment]
Did you do like this:

```
`cd /tmp
 git clone git@github.com:SOII-2016/shue.git
 git clone git@gitlab.com:monaco/posixeg.git
 cd shue
 cd runcmd    # Your path is myproject/runcmd, it should be runcmd instead
 make
 make PREFIX="/tmp/foo" install
 cd ../posixeg
 make clean
 make LDFLAGS="-L/tmp/foo/lib -Wl,-rpath=/tmp/foo/lib" \
          CPPFLAGS="-I/tmp/fool/include" test-runcmd
 make test
`
```

**Comment by monacofj** [comment]
LDFLAGS="-L"path to our project"/lib ?


[]'s monaco

------------------------------------------------------------
Prof. Dr. Monaco F. J.
Department of Computer Systems - ICMC
University of São Paulo

**Comment by Henrique1792** [comment]
Everything set up fine!
