### ISSUE TITLE
[Runcmd] Issues

### ISSUE THREAD

**Issue by Henrique1792** [SOII-2016/shue#6]
##Comments
Well, good morning/afternoon/evening!

We got some questions about how we implemented some stuff, so here we go:
  1. We redirect fd's before 'fork' call. Is it right this way?
  2. At NonBlock execution, we exec it and raise a SIGKILL. I dunno if it works well - at least a kill
defined by the program doesn't look like a SUCCESS finish.
  3. How we're supposed to deal with signals here?

*Thanks for the help*

**Comment by monacofj** [comment]
1. If I got you right, I guess if you redirect before forking, the caller's will also have their standard streams redirected. That is not good. Unless you revert it before returning from the function call.

2. How would it be supposed to work? I'm afraid I haven't understood the strategy...

3. The only signal handling I can figure out is for SIGCHLD if user specifies a call-back in a nonblocking invocation.

**Comment by Henrique1792** [comment]
1. I redirect it this way 'cause the child uses the fd's defined. After **wait** call, we recover the std in/out/err.

2. We execute the child proccess and kill it using raise(SIGKILL), in order to eliminate the zombie proccess. I dunno if it's right that way.

**Comment by monacofj** [comment]
1. Fine if you restore original standard streams before returning from the function. Another strategy, which I would consider myself, would be to redirect IO in the child process right before exec call. 

2. As any good and well-behavior zombie, defunct processes can't be killed, unless with a shot-in-the-head, what in POSIX is a call to wait.  It happens that a zombie process won't receive signals, and won't be affected even by SIGKILL.  You may fire at will and they will be there, walking erratically, until you wait on their souls.  Well, process zombies ca't support orphanhood, as well; they die if their parents are killed (this is a second way to get rid of zombies: kill the parent).
