### ISSUE TITLE
[RunCmd] New makefile linking changes

### ISSUE THREAD

**Issue by meist3r-ed** [SOII-2016/shue#8]
Hello there everyone!
We've just pulled the most recent commit from the POSIXeg for updates and changes, and we've crossed with a minor problem: there were changes made over the Makefile and there are new linking directives for compiling and executing the exercise's files. We have already made the changes from past exercises and currently that's the only thing that is blocking our way.
Thanks in advance!

**Comment by Henrique1792** [comment]
I don't understand why it isn't linking... Do we need to use autotools now to link it right??

**Comment by monacofj** [comment]
Would you lost the error output?

**Comment by Henrique1792** [comment]
I'll set it today and check it out
